name: Gas Snapshot

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  gas-snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Cache Foundry
        uses: actions/cache@v4
        with:
          path: |
            ~/.foundry/cache
            ~/.cache/foundry
            lib
          key: ${{ runner.os }}-foundry-${{ hashFiles('foundry.toml', 'lib/**') }}

      - name: Install dependencies
        run: |
          forge --version
          forge install

      - name: Build
        run: make build

      - name: Run gas snapshot
        run: make snapshot

      - name: Save PR snapshot
        run: cp gas-snapshot gas-snapshot.pr

      - name: Get base gas snapshot
        run: |
          git checkout origin/${{ github.base_ref }} -- gas-snapshot || echo "" > gas-snapshot.base
          [ -f gas-snapshot.base ] || mv gas-snapshot gas-snapshot.base

      - name: Generate diff
        id: diff
        run: |
          echo '```diff' > gas-diff.txt
          diff -u gas-snapshot.base gas-snapshot.pr || true >> gas-diff.txt
          echo '```' >> gas-diff.txt
          echo "diff<<EOF" >> $GITHUB_OUTPUT
          cat gas-diff.txt >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT

      - name: Comment diff on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: gas-snapshot
          message: |
            Gas snapshot diff (base vs PR):

            ${{ steps.diff.outputs.diff }}
